### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by belozyorcev** [voischev/bem-full-stack#13]
Как собирать бандлы? В проекте не вижу ни enb ни bem-tools. Жалуется на отсутствие бандла.

```
> bem-full-stack@0.0.3 start /home/sergey/sandbox/test-full-stack
> node server/app.js

module.js:328
    throw err;
    ^

Error: Cannot find module '/home/sergey/sandbox/test-full-stack/build/bundles/index/index.bemtree.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/sergey/sandbox/test-full-stack/server/render.js:16:19
    at Array.forEach (native)
    at Object.<anonymous> (/home/sergey/sandbox/test-full-stack/server/render.js:14:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

```

**Comment by belozyorcev** [comment]
Хотя сейчас запустил просто npm start и всё заработало

**Comment by voischev** [comment]
Закроешь ишью?
